services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    build:
      context: containers/mediamtx
    restart: always
    volumes:
      - ./containers/mediamtx/mediamtx.yml:/mediamtx.yml
      - ./containers/mediamtx/recordings:/recordings

  cam1:
    image: bluenviron/mediamtx:latest-ffmpeg
    build:
      context: containers/mediamtx
    restart: always
    volumes:
      - ./containers/cam1/mediamtx.yml:/mediamtx.yml

  #cam1_ffmpeg:
  #  image: linuxserver/ffmpeg
  #  # ingest to nimble:
  #  #command: -re -f lavfi -i testsrc2=size=3840x2160:rate=60 -f lavfi -i aevalsrc="sin(0*2*PI*t)" -c:v libx264 -r 30 -g 30 -preset fast -vb 8000k -pix_fmt rgb24 -pix_fmt yuv420p -f rtsp rtsp://ingest:6S3LiiD3897Ap3oQsT7X53aTEthKGF@nimble:20001/pollinator-demo/cam1
  #  # ingest to mediamts:
  #  command: -re -f lavfi -i testsrc2=size=3840x2160:rate=60 -f lavfi -i aevalsrc="sin(0*2*PI*t)" -c:v libx264 -r 30 -g 30 -preset fast -vb 8000k -pix_fmt rgb24 -pix_fmt yuv420p -f srt "srt://mediamtx:8890/?streamid=publish:cam1&pkt_size=1316"
  #  #depends_on:
  #  #  nimble:
  #  #    condition: service_healthy
