services:
  chatbot:
    build:
      context: containers/chatbot/app
    environment:
      - TWITCH_CHANNELS=${TWITCH_CHANNELS}
      - ALVEUS_CLIENT_ID=${ALVEUS_CLIENT_ID}
      - ALVEUS_CLIENT_SECRET=${ALVEUS_CLIENT_SECRET}
      - ALVEUS_TWITCH_ID=${ALVEUS_TWITCH_ID}
      - ALVEUS_TOKEN_PATH=../tokens/tokens.json
      - TWITCH_TOKEN_PATH=/tokens/tokens.json
      - OBS_WS=${OBS_WS}
      - OBS_KEY=
      - OBS_WS_SPACE_CLOUD=ws://obs-cloud:12345
      - OBS_KEY_SPACE_CLOUD=
      - OBSBOT_HOST=localhost
      - OBSBOT_PORT=12345
    depends_on:
      - obs-local
      - obs-cloud
    volumes:
      - ./containers/chatbot/data:/home/node/app/src/data
      - ./containers/chatbot/tokens:/home/node/app/tokens

  cam-proxy:
    image: bluenviron/mediamtx:latest-ffmpeg
    build:
      context: containers/cam-proxy
    restart: always
    environment:
      - MTX_PROTOCOLS=tcp
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
      - "9996:9996"
    volumes:
      - ./containers/cam-proxy/mediamtx.yml:/mediamtx.yml
      - ./containers/cam-proxy/recordings:/recordings

  cam:
    image: bluenviron/mediamtx:latest-ffmpeg
    build:
      context: containers/cam
    restart: always
    volumes:
      - ./containers/cam/mediamtx.yml:/mediamtx.yml

  obs-local:
    build: containers/obs-mock
    environment:
      - PORT=12345
    expose:
      - "12345"

  obs-cloud:
    build: containers/obs-mock
    environment:
      - PORT=12345
    expose:
      - "12345"